### ISSUE TITLE
Screenshots taken by maim do not show up as "recent files"

### ISSUE THREAD

**Issue by j-james** [naelstrof/maim#219]
When taking a screenshot, the screenshot doesn't show up as a "recent file" in (at least) applications using GtkFileChooser. 

Screenshots taken by `xfce4-screenshooter` do appear.

**Comment by foxpy** [comment]
For this to work, maim should now rely on GTK. There is already a bunch of dependencies, is it worth it to bring yet another one?

**Comment by naelstrof** [comment]
A small python script could handle this. Some casual google searches came up with this: https://stackoverflow.com/questions/39836725/how-does-one-add-an-item-to-gtks-recently-used-file-list-from-python/39927261

I think it's outside the scope of maim to do this automatically, since there's no guarantee someone's using GTK.
