### ISSUE TITLE
GLEW is also a requisite for installing maim 

### ISSUE THREAD

**Issue by BuddhiLW** [naelstrof/maim#239]
I would make a pull request, but it's a simple issue.

I was unable to fresh install maim, because I didn't have GLEW installed. So, I would add that on the documentations, when mentioning cmake.

**Comment by foxpy** [comment]
On the slop repo it is mentioned that GLEW is required, and since slop is a dependency of maim, everything seems alright.

**BUT!**

A build process of slop is mentioned in README for maim, so it really needs to have GLEW mentioned as a requisite. There is also libxext mentioned on the slop page, we should probably add this too.

So, in conclusion, not only GLEW, but also libxext.
