### ISSUE TITLE
-g option malfunction

### ISSUE THREAD

**Issue by mcnuggetsx20** [naelstrof/maim#251]
Using `maim -g 1920x1080+1920+0` to take a screenshot of the other monitor produces a larger file than usual (1.8MB). `maim -g 1920x1080` produces a file of size 700KB.

**Comment by foxpy** [comment]
I would be glad to be able to download resulting files.

**Comment by mcnuggetsx20** [comment]
As it turns out, the size of the image depends on what window is now on the screen. That is weird.

https://drive.google.com/drive/folders/1i87ErkXwTxcYeE7gn5iQZradqCsawzqr?usp=sharing

The first image is a screenshot of my terminal and the second one is the screenshot of me writing this reply. Both of them were taken on the same screen but the sizes are drastically different. Maybe it's something you guys intended to do but I find it really odd.

**Comment by foxpy** [comment]
These are PNG images. [PNG](https://en.wikipedia.org/wiki/Portable_Network_Graphics) is a lossless compression format. Compression ratio depends on input image. Simplest image (blank picture) leads to almost zero file size and grey noise leads to absolutely no compression benefits.

If you don't like this behaviour, you can output images in BMP format (`maim --format=bmp`), but why would you want that? It wastes disk space, and it wastes bandwidth if you want to send pictures over Internet.

**Comment by mcnuggetsx20** [comment]
I have a script to take a screenshot and copy it to the clipboard. An image which is almost 2MB in size causes my browser to lag when I paste it.

**Comment by foxpy** [comment]
> image causes my browser to lag when I paste it

If that's actually your problem you are willing to solve, please consider reopening this issue and providing some more information:
- script source code;
- sample images which cause problems (please consider avoiding garbage "cloud storage" websites like Google Drive in future when submitting files to open source maintainers, it is really unpleasant for us because we cannot simply download files via a direct link and have to click around their crappy web UI. Good example of convenient file hosting is https://0x0.st/);
- exact application causing your issue (I mean, web browser version and probably web page you are pasting into).
