### ISSUE TITLE
maim doesnt pipe output to clipboard using xclip inside WM config; does outside

### ISSUE THREAD

**Issue by Eliiia** [naelstrof/maim#262]
while the name is similar to #205, im very doubtful its the same issue
running: 
- arch linux (kernel `5.18.16-arch1-1`)
- maim v5.7.4
- openbox v3.6.1

this command works entirely fine in terminal, but fails to run inside openbox as a keybind: `maim -s -u -k | xclip -selection clipboard -t image/png -i`

i have confirmed that running `maim -s -u -k ~/Pictures/screenshot_$(date +%s).png` works both inside and outside the openbox config
i used scrot before this, with no issues

here is the relevant openbox rc.xml:
```xml
    <!-- Screenshots -->
    <keybind key="Print">
      <action name="Execute">
        <command>maim -s -u -k | xclip -selection clipboard -t image/png -i</command>
      </action>
    </keybind>
```

maybe the command just doesnt work on openbox? in my experience though, openbox usually complains about that. 
either way, im stuck, and have been for a few days; any help would be very appreciated. thank you!!

**Comment by foxpy** [comment]
Sounds like openbox tries to execute `maim` with arguments `-s -u -k | xclip -selection clipboard -t image/png -i`, which is incorrect, since you actually want to run two different programs. I suggest you trying to wrap your command in `sh -c`, e.g. `sh -c 'maim -s -u -k | xclip -selection clipboard -t image/png -i'`. Does it work for you now?

**Comment by Eliiia** [comment]
huh, it does! thank you so much, and sorry for bothering you; i was unsure what this could be apart from maim refusing to run in this sort of environment. thank you, seriously :)
