### ISSUE TITLE
config file to set destination directory to something other than $HOME

### ISSUE THREAD

**Issue by patrickod** [naelstrof/maim#36]
my use case for maim at the moment using using it w/ i3 to exec `maim -s` and take a screenshot, then fetching the file from my home directory.

I'd love to be able to set a destination directory for the resulting images that isn't my home directory. I looked through the man page and didn't see anything to this effect.

**Comment by naelstrof** [comment]
You mean like `maim -s /tmp/blah.png`?

In the man page it specifies the Usage as `maim [options] [file]` where file is the destination directory.

Unless you mean something else?

**Comment by patrickod** [comment]
more I think it's possible to cut out a decent amount of repetition for
users with a one-liner config file.

I think for the moment it might be best to define an alias that does
this if maim as a codebase does not wish to have this functionality.

**Comment by naelstrof** [comment]
I do not see the advantages to adding the functionaility to maim, when the same functionality already exists in scripts or aliases.

I recently had the same thoughts about a delay timer, but ultimately added it in since it's way easier to type `maim -d5` than `sleep 5;maim`.

However, in this case, either way you'd be messing with configuration files. So I do not see the benefit.

**Comment by patrickod** [comment]
yep 100% a fair point. I can see the benefit of keeping maim as simple as is possible. In this case a script / alias will suffice. 

Definitely appreciate the back and forth here. I love maim, it's one of my favourite GitHub finds of the last year. Thanks for putting it out there and shepherding it!

**Comment by naelstrof** [comment]
I appreciate the feedback! It's the only thing I'm getting paid with :heart:.
