### ISSUE TITLE
write scrots to stdout?

### ISSUE THREAD

**Issue by tb01110100** [naelstrof/maim#37]
I'd like to be able to output screenshots to stdout.

**Comment by naelstrof** [comment]
Heh alright, I actually thought of this as something that could be useful but disregarded it as I couldn't think of an actual use.

For now you can use something like maim /tmp/blah.png;cat /tmp/blah.png, but I'll look into implementing it.

**Comment by naelstrof** [comment]
My initial findings are that imlib2 provides no support for saving formatted image data directly to stdout.

It's hardcoded to save to a file so badly that in order to redirect file saving to stdout I would have to reprogram each individual filetype module's save function. (There's 14 of them)
 Each module specifically saves to a file stream that's created and destroyed within the module's save function itself.

The easiest way to provide full support for this would be to save the screenshot normally and then print its contents to stdout. Which can already be done with `maim /tmp/blah.png;cat /tmp/blah.png`

Alternatively I could provide gimped support by only supporting raw image data being put into stdout.

But for the time being I'm going to try to fix the problem upstream, I'll make a patch and see if they'll accept it.

**Comment by HalosGhost** [comment]
Any update on the progress for this? It'd be very helpful to be able to, for example, pipe the image directly into a cli pastebin utility.

:+1: for supporting this (upstream support would, of course, be ideal).

**Comment by naelstrof** [comment]
I contacted a Imlib2 developer, he said Imlib2 is dead.
I don't want to include a whole new custom imlib2 (imlib3? lmao) in maim just for this feature, however I'm going to look into alternatives to imlib2, supposedly the Enlightenment team is working on a "bigger and better" version.

**Comment by HalosGhost** [comment]
D: Oh well then…

**Comment by naelstrof** [comment]
With b9c44d8e4799e3c55ffb236300683c98fec8382a, you can now do
`maim -f png /dev/stdout`
Depending on your system, it should provide the desired effect. Close the issue if you think that's adequate.

**Comment by tb01110100** [comment]
Ooh, very nice. Thanks!

**Comment by HalosGhost** [comment]
:+1:
