### ISSUE TITLE
Visual countdown

### ISSUE THREAD

**Issue by Brottweiler** [naelstrof/maim#56]
scrot has a way to visually show the countdown, like so:
![image](https://cloud.githubusercontent.com/assets/1613137/13872047/a6bb9e7a-ece7-11e5-9a11-bcd51f74df6f.png)

You can see so in the manpage that the `-c` option provides this, and you need to use this with the `-d` option; `scrot -cd 5`

```man
       -c, --count
            Display a countdown when used with delay.

       -d, --delay NUM
            Wait NUM seconds before taking a shot.
```

maim does only have the `delay` option. My feature request, I guess, is to add an option to do visual countdown. The `-c` option is used with slop though I think so maybe it's necessary to find another option to use. `-c` would be convenient since it's the same for scrot, though.

```man
  -d, --delay=FLOAT             Set the amount of time to wait before taking an
                                  image.  (default=`0.0')
```

**Comment by onodera-punpun** [comment]
IMO, this is not something maims should do, here is a simple script that does exactly the same:

```
#!/bin/bash
for i in {5..0}; do
	echo -n "$i.. "
	sleep 1
done
maim
```

**Comment by naelstrof** [comment]
I agree with punpun for this one. maim shouldn't guide people astray from the power of the terminal. So I won't add this for the same reason I didn't add the `--exec` feature, though I won't remove the delay option for compatibility sake.

Nobody would like their scripts breaking or acting inconsistently because I remove an undesired feature. I kinda know how Microsoft feels now.
